//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.10.19 at 01:36:41 PM PDT 
//

package com.facebook.infrastructure.loader;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for KeyType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;KeyType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;OptimizeIt&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}boolean&quot;/&gt;
 *         &lt;element name=&quot;Combiner&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;Fields&quot; type=&quot;{}FieldCollection&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KeyType", propOrder = { "optimizeIt", "combiner", "fields" })
public class KeyType {

  @XmlElement(name = "OptimizeIt", required = true, type = Boolean.class, nillable = true)
  protected Boolean optimizeIt;
  @XmlElement(name = "Combiner", required = true)
  protected String combiner;
  @XmlElement(name = "Fields", required = true)
  protected FieldCollection fields;

  /**
   * Gets the value of the optimizeIt property.
   * 
   * @return possible object is {@link Boolean }
   * 
   */
  public Boolean isOptimizeIt() {
    return optimizeIt;
  }

  /**
   * Sets the value of the optimizeIt property.
   * 
   * @param value
   *          allowed object is {@link Boolean }
   * 
   */
  public void setOptimizeIt(Boolean value) {
    this.optimizeIt = value;
  }

  /**
   * Gets the value of the combiner property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCombiner() {
    return combiner;
  }

  /**
   * Sets the value of the combiner property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setCombiner(String value) {
    this.combiner = value;
  }

  /**
   * Gets the value of the fields property.
   * 
   * @return possible object is {@link FieldCollection }
   * 
   */
  public FieldCollection getFields() {
    return fields;
  }

  /**
   * Sets the value of the fields property.
   * 
   * @param value
   *          allowed object is {@link FieldCollection }
   * 
   */
  public void setFields(FieldCollection value) {
    this.fields = value;
  }

}
